# Generated by Django 5.0.6 on 2025-05-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_change_default_currency_to_inr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anomaly_detection_sensitivity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='anomaly_min_amount',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_anomaly_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
